mode:
  config: dev 

local:
  dbName: papahana 
  obCollect: observation_blocks
  observerCollect: observer
  containerCollect: containers
  scriptCollect: scripts
  templateCollect: templates
  ipCollect: instrument_packages
  port: 27017
  ip: 
demo:
  dbName: papahana 
  obCollect: observation_blocks
  observerCollect: observer
  containerCollect: containers
  scriptCollect: scripts
  templateCollect: templates
  ipCollect: instrument_packages
  ip:
  port: 27017
dev:
  dbName: papahana_test
  obCollect: observation_blocks
  observerCollect: observer
  containerCollect: containers
  scriptCollect: scripts
  templateCollect: templates
  ipCollect: instrument_packages
  port: 27017 
  ip: 
test:
  dbName: papahana_test
  obCollect: observation_blocks
  observerCollect: observer
  containerCollect: containers
  scriptCollect: scripts
  templateCollect: templates
  ipCollect: instrument_packages
  port: 27017
  ip: 


apis:
  proposalApi: https://www.keck.hawaii.edu/software/db_api/proposalsAPI.php

