mode:
  config: dev 

local:
  dbName: papahana 
  obCollect: observation_blocks
  containerCollect: containers
  templateCollect: templates
  ipCollect: instrument_packages
  port: 27017
  ip: 10.96.0.228
demo:
  dbName: papahana 
  obCollect: observation_blocks
  containerCollect: containers
  templateCollect: templates
  ipCollect: instrument_packages
  ip: 127.0.0.1
  port: 27017
dev:
  dbName: papahana
  obCollect: observation_blocks
  containerCollect: containers
  templateCollect: templates
  ipCollect: instrument_packages
  port: 27017
  ip: 10.96.0.228
test:
  dbName: papahana_test
  obCollect: observation_blocks
  containerCollect: containers
  templateCollect: templates
  ipCollect: instrument_packages
  port: 27017
  ip: 10.96.0.228


apis:
  proposalApi: https://www.keck.hawaii.edu/software/db_api/proposalsAPI.php

