mode:
  config: dev 

local:
  dbName: papahana 
  obCollect: ob_blocks
  containerCollect: containers
  prgCollect: programs
  port: 27017
  password: ...
  username: ...
demo:
  dbName: papahana 
  obCollect: ob_blocks
  containerCollect: containers
  prgCollect: programs
  port: 27017
  password: ...
  username: ...
dev:
  dbName: papahana
  obCollect: ob_blocks
  containerCollect: containers
  prgCollect: programs
  port: 27017

urls:
  proposalApi: https://www.keck.hawaii.edu/software/db_api/proposalsAPI.php?

