mode:
  config: dev 

local:
  dbName: papahana 
  obCollect: ob_blocks
  groupCollect: groups
  prgCollect: programs
  port: 27017
  password: ...
  username: ...
demo:
  dbName: papahana 
  obCollect: ob_blocks
  groupCollect: groups
  prgCollect: programs
  port: 27017
  password: ...
  username: ...
dev:
  dbName: papahana
  obCollect: ob_blocks
  groupCollect: groups
  prgCollect: programs
  port: 27017
