openapi: 3.0.0
info:
  title: Papahana_demo
  description: WMKO API to the Observation Management System
  contact:
    email: observing-support@keck.hawaii.edu
  license:
    name: BSD 3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  version: "0.1"
servers:
- url: http://localhost:8080/v0
tags:
- name: Observation Block
  externalDocs:
    description: Find out more
    url: https://keckobservatory.atlassian.net/wiki/spaces/DSI/pages/808779858/Programmatic+Web+Interfacej
- name: Group
  externalDocs:
    description: Find out more
    url: https://keckobservatory.atlassian.net/wiki/spaces/DSI/pages/808779858/Programmatic+Web+Interfacej
paths:
  /groups:
    $ref: "#./paths/groups/group.yaml"
  /groups/append:
    $ref: "#./paths/groups/groups_append.yaml"
  /groups/executionTimes:
    $ref: "#./paths/groups/groups_execution_time.yaml"
  /groups/items:
    $ref: "#./paths/groups/groups_items.yaml"
  /groups/items/summary:
    $ref: "#./paths/groups/groups_items_summary.yaml"
  /groups/verify:
    $ref: "#./paths/groups/groups_verify.yaml"
  /groups/scheduleToO:
    $ref: "#./paths/groups/groups_too.yaml"
  /groups/export:
    $ref: "#./paths/groups/groups_export.yaml"
  /obsBlocks/:
    $ref: "#./paths/ob_blocks/obs_blocks.yaml"
  /obsBlocks/duplicate/{sem_id}:
    $ref: "#./paths/ob_blocks/obs_blocks_duplicate.yaml"
components:
  schemas:
    $ref: "./schemas/_index.yaml"
  parameters:
    $ref: "./parameters/_index.yaml"