# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DefaultAcquisition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, instrumental_setup: str=None, acquisition_method: str=None, guider_selection: str=None, ao_modes: List[str]=None, associations: List[str]=None, offset_stars: List[str]=None, slitmasks: List[str]=None, position_angles: List[str]=None):  # noqa: E501
        """DefaultAcquisition - a model defined in Swagger

        :param instrumental_setup: The instrumental_setup of this DefaultAcquisition.  # noqa: E501
        :type instrumental_setup: str
        :param acquisition_method: The acquisition_method of this DefaultAcquisition.  # noqa: E501
        :type acquisition_method: str
        :param guider_selection: The guider_selection of this DefaultAcquisition.  # noqa: E501
        :type guider_selection: str
        :param ao_modes: The ao_modes of this DefaultAcquisition.  # noqa: E501
        :type ao_modes: List[str]
        :param associations: The associations of this DefaultAcquisition.  # noqa: E501
        :type associations: List[str]
        :param offset_stars: The offset_stars of this DefaultAcquisition.  # noqa: E501
        :type offset_stars: List[str]
        :param slitmasks: The slitmasks of this DefaultAcquisition.  # noqa: E501
        :type slitmasks: List[str]
        :param position_angles: The position_angles of this DefaultAcquisition.  # noqa: E501
        :type position_angles: List[str]
        """
        self.swagger_types = {
            'instrumental_setup': str,
            'acquisition_method': str,
            'guider_selection': str,
            'ao_modes': List[str],
            'associations': List[str],
            'offset_stars': List[str],
            'slitmasks': List[str],
            'position_angles': List[str]
        }

        self.attribute_map = {
            'instrumental_setup': 'instrumental_setup',
            'acquisition_method': 'acquisition_method',
            'guider_selection': 'guider_selection',
            'ao_modes': 'ao_modes',
            'associations': 'associations',
            'offset_stars': 'offset_stars',
            'slitmasks': 'slitmasks',
            'position_angles': 'position_angles'
        }
        self._instrumental_setup = instrumental_setup
        self._acquisition_method = acquisition_method
        self._guider_selection = guider_selection
        self._ao_modes = ao_modes
        self._associations = associations
        self._offset_stars = offset_stars
        self._slitmasks = slitmasks
        self._position_angles = position_angles

    @classmethod
    def from_dict(cls, dikt) -> 'DefaultAcquisition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DefaultAcquisition of this DefaultAcquisition.  # noqa: E501
        :rtype: DefaultAcquisition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def instrumental_setup(self) -> str:
        """Gets the instrumental_setup of this DefaultAcquisition.


        :return: The instrumental_setup of this DefaultAcquisition.
        :rtype: str
        """
        return self._instrumental_setup

    @instrumental_setup.setter
    def instrumental_setup(self, instrumental_setup: str):
        """Sets the instrumental_setup of this DefaultAcquisition.


        :param instrumental_setup: The instrumental_setup of this DefaultAcquisition.
        :type instrumental_setup: str
        """
        if instrumental_setup is None:
            raise ValueError("Invalid value for `instrumental_setup`, must not be `None`")  # noqa: E501

        self._instrumental_setup = instrumental_setup

    @property
    def acquisition_method(self) -> str:
        """Gets the acquisition_method of this DefaultAcquisition.


        :return: The acquisition_method of this DefaultAcquisition.
        :rtype: str
        """
        return self._acquisition_method

    @acquisition_method.setter
    def acquisition_method(self, acquisition_method: str):
        """Sets the acquisition_method of this DefaultAcquisition.


        :param acquisition_method: The acquisition_method of this DefaultAcquisition.
        :type acquisition_method: str
        """
        if acquisition_method is None:
            raise ValueError("Invalid value for `acquisition_method`, must not be `None`")  # noqa: E501

        self._acquisition_method = acquisition_method

    @property
    def guider_selection(self) -> str:
        """Gets the guider_selection of this DefaultAcquisition.


        :return: The guider_selection of this DefaultAcquisition.
        :rtype: str
        """
        return self._guider_selection

    @guider_selection.setter
    def guider_selection(self, guider_selection: str):
        """Sets the guider_selection of this DefaultAcquisition.


        :param guider_selection: The guider_selection of this DefaultAcquisition.
        :type guider_selection: str
        """
        if guider_selection is None:
            raise ValueError("Invalid value for `guider_selection`, must not be `None`")  # noqa: E501

        self._guider_selection = guider_selection

    @property
    def ao_modes(self) -> List[str]:
        """Gets the ao_modes of this DefaultAcquisition.


        :return: The ao_modes of this DefaultAcquisition.
        :rtype: List[str]
        """
        return self._ao_modes

    @ao_modes.setter
    def ao_modes(self, ao_modes: List[str]):
        """Sets the ao_modes of this DefaultAcquisition.


        :param ao_modes: The ao_modes of this DefaultAcquisition.
        :type ao_modes: List[str]
        """
        if ao_modes is None:
            raise ValueError("Invalid value for `ao_modes`, must not be `None`")  # noqa: E501

        self._ao_modes = ao_modes

    @property
    def associations(self) -> List[str]:
        """Gets the associations of this DefaultAcquisition.


        :return: The associations of this DefaultAcquisition.
        :rtype: List[str]
        """
        return self._associations

    @associations.setter
    def associations(self, associations: List[str]):
        """Sets the associations of this DefaultAcquisition.


        :param associations: The associations of this DefaultAcquisition.
        :type associations: List[str]
        """
        if associations is None:
            raise ValueError("Invalid value for `associations`, must not be `None`")  # noqa: E501

        self._associations = associations

    @property
    def offset_stars(self) -> List[str]:
        """Gets the offset_stars of this DefaultAcquisition.


        :return: The offset_stars of this DefaultAcquisition.
        :rtype: List[str]
        """
        return self._offset_stars

    @offset_stars.setter
    def offset_stars(self, offset_stars: List[str]):
        """Sets the offset_stars of this DefaultAcquisition.


        :param offset_stars: The offset_stars of this DefaultAcquisition.
        :type offset_stars: List[str]
        """
        if offset_stars is None:
            raise ValueError("Invalid value for `offset_stars`, must not be `None`")  # noqa: E501

        self._offset_stars = offset_stars

    @property
    def slitmasks(self) -> List[str]:
        """Gets the slitmasks of this DefaultAcquisition.


        :return: The slitmasks of this DefaultAcquisition.
        :rtype: List[str]
        """
        return self._slitmasks

    @slitmasks.setter
    def slitmasks(self, slitmasks: List[str]):
        """Sets the slitmasks of this DefaultAcquisition.


        :param slitmasks: The slitmasks of this DefaultAcquisition.
        :type slitmasks: List[str]
        """
        if slitmasks is None:
            raise ValueError("Invalid value for `slitmasks`, must not be `None`")  # noqa: E501

        self._slitmasks = slitmasks

    @property
    def position_angles(self) -> List[str]:
        """Gets the position_angles of this DefaultAcquisition.


        :return: The position_angles of this DefaultAcquisition.
        :rtype: List[str]
        """
        return self._position_angles

    @position_angles.setter
    def position_angles(self, position_angles: List[str]):
        """Sets the position_angles of this DefaultAcquisition.


        :param position_angles: The position_angles of this DefaultAcquisition.
        :type position_angles: List[str]
        """
        if position_angles is None:
            raise ValueError("Invalid value for `position_angles`, must not be `None`")  # noqa: E501

        self._position_angles = position_angles
