# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Magnitude(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, band: str=None, mag: float=None):  # noqa: E501
        """Magnitude - a model defined in Swagger

        :param band: The band of this Magnitude.  # noqa: E501
        :type band: str
        :param mag: The mag of this Magnitude.  # noqa: E501
        :type mag: float
        """
        self.swagger_types = {
            'band': str,
            'mag': float
        }

        self.attribute_map = {
            'band': 'band',
            'mag': 'mag'
        }
        self._band = band
        self._mag = mag

    @classmethod
    def from_dict(cls, dikt) -> 'Magnitude':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Magnitude of this Magnitude.  # noqa: E501
        :rtype: Magnitude
        """
        return util.deserialize_model(dikt, cls)

    @property
    def band(self) -> str:
        """Gets the band of this Magnitude.


        :return: The band of this Magnitude.
        :rtype: str
        """
        return self._band

    @band.setter
    def band(self, band: str):
        """Sets the band of this Magnitude.


        :param band: The band of this Magnitude.
        :type band: str
        """
        if band is None:
            raise ValueError("Invalid value for `band`, must not be `None`")  # noqa: E501

        self._band = band

    @property
    def mag(self) -> float:
        """Gets the mag of this Magnitude.


        :return: The mag of this Magnitude.
        :rtype: float
        """
        return self._mag

    @mag.setter
    def mag(self, mag: float):
        """Sets the mag of this Magnitude.


        :param mag: The mag of this Magnitude.
        :type mag: float
        """
        if mag is None:
            raise ValueError("Invalid value for `mag`, must not be `None`")  # noqa: E501

        self._mag = mag
