# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Program(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, sem_id: str=None, observation_blocks: List[str]=None):  # noqa: E501
        """Program - a model defined in Swagger

        :param name: The name of this Program.  # noqa: E501
        :type name: str
        :param sem_id: The sem_id of this Program.  # noqa: E501
        :type sem_id: str
        :param observation_blocks: The observation_blocks of this Program.  # noqa: E501
        :type observation_blocks: List[str]
        """
        self.swagger_types = {
            'name': str,
            'sem_id': str,
            'observation_blocks': List[str]
        }

        self.attribute_map = {
            'name': 'name',
            'sem_id': 'sem_id',
            'observation_blocks': 'observation_blocks'
        }
        self._name = name
        self._sem_id = sem_id
        self._observation_blocks = observation_blocks

    @classmethod
    def from_dict(cls, dikt) -> 'Program':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Program of this Program.  # noqa: E501
        :rtype: Program
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Program.


        :return: The name of this Program.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Program.


        :param name: The name of this Program.
        :type name: str
        """

        self._name = name

    @property
    def sem_id(self) -> str:
        """Gets the sem_id of this Program.


        :return: The sem_id of this Program.
        :rtype: str
        """
        return self._sem_id

    @sem_id.setter
    def sem_id(self, sem_id: str):
        """Sets the sem_id of this Program.


        :param sem_id: The sem_id of this Program.
        :type sem_id: str
        """

        self._sem_id = sem_id

    @property
    def observation_blocks(self) -> List[str]:
        """Gets the observation_blocks of this Program.


        :return: The observation_blocks of this Program.
        :rtype: List[str]
        """
        return self._observation_blocks

    @observation_blocks.setter
    def observation_blocks(self, observation_blocks: List[str]):
        """Sets the observation_blocks of this Program.


        :param observation_blocks: The observation_blocks of this Program.
        :type observation_blocks: List[str]
        """

        self._observation_blocks = observation_blocks
