# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Program(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, semester: str=None, observation_blocks: List[str]=None):  # noqa: E501
        """Program - a model defined in Swagger

        :param semester: The semester of this Program.  # noqa: E501
        :type semester: str
        :param observation_blocks: The observation_blocks of this Program.  # noqa: E501
        :type observation_blocks: List[str]
        """
        self.swagger_types = {
            'semester': str,
            'observation_blocks': List[str]
        }

        self.attribute_map = {
            'semester': 'semester',
            'observation_blocks': 'observation_blocks'
        }
        self._semester = semester
        self._observation_blocks = observation_blocks

    @classmethod
    def from_dict(cls, dikt) -> 'Program':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Program of this Program.  # noqa: E501
        :rtype: Program
        """
        return util.deserialize_model(dikt, cls)

    @property
    def semester(self) -> str:
        """Gets the semester of this Program.


        :return: The semester of this Program.
        :rtype: str
        """
        return self._semester

    @semester.setter
    def semester(self, semester: str):
        """Sets the semester of this Program.


        :param semester: The semester of this Program.
        :type semester: str
        """

        self._semester = semester

    @property
    def observation_blocks(self) -> List[str]:
        """Gets the observation_blocks of this Program.


        :return: The observation_blocks of this Program.
        :rtype: List[str]
        """
        return self._observation_blocks

    @observation_blocks.setter
    def observation_blocks(self, observation_blocks: List[str]):
        """Sets the observation_blocks of this Program.


        :param observation_blocks: The observation_blocks of this Program.
        :type observation_blocks: List[str]
        """

        self._observation_blocks = observation_blocks
