# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Semester(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, semester: str=None):  # noqa: E501
        """Semester - a model defined in Swagger

        :param semester: The semester of this Semester.  # noqa: E501
        :type semester: str
        """
        self.swagger_types = {
            'semester': str
        }

        self.attribute_map = {
            'semester': 'semester'
        }
        self._semester = semester

    @classmethod
    def from_dict(cls, dikt) -> 'Semester':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Semester of this Semester.  # noqa: E501
        :rtype: Semester
        """
        return util.deserialize_model(dikt, cls)

    @property
    def semester(self) -> str:
        """Gets the semester of this Semester.


        :return: The semester of this Semester.
        :rtype: str
        """
        return self._semester

    @semester.setter
    def semester(self, semester: str):
        """Sets the semester of this Semester.


        :param semester: The semester of this Semester.
        :type semester: str
        """

        self._semester = semester
