# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana import util


class AcquisitionParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tcs_coord_po: str=None):  # noqa: E501
        """AcquisitionParameters - a model defined in Swagger

        :param tcs_coord_po: The tcs_coord_po of this AcquisitionParameters.  # noqa: E501
        :type tcs_coord_po: str
        """
        self.swagger_types = {
            'tcs_coord_po': str
        }

        self.attribute_map = {
            'tcs_coord_po': 'tcs_coord_po'
        }
        self._tcs_coord_po = tcs_coord_po

    @classmethod
    def from_dict(cls, dikt) -> 'AcquisitionParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AcquisitionParameters of this AcquisitionParameters.  # noqa: E501
        :rtype: AcquisitionParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tcs_coord_po(self) -> str:
        """Gets the tcs_coord_po of this AcquisitionParameters.


        :return: The tcs_coord_po of this AcquisitionParameters.
        :rtype: str
        """
        return self._tcs_coord_po

    @tcs_coord_po.setter
    def tcs_coord_po(self, tcs_coord_po: str):
        """Sets the tcs_coord_po of this AcquisitionParameters.


        :param tcs_coord_po: The tcs_coord_po of this AcquisitionParameters.
        :type tcs_coord_po: str
        """
        if tcs_coord_po is None:
            raise ValueError("Invalid value for `tcs_coord_po`, must not be `None`")  # noqa: E501

        self._tcs_coord_po = tcs_coord_po
