# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana.models.observation_metadata import ObservationMetadata  # noqa: F401,E501
from papahana import util


class CalEngTemplate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metadata: ObservationMetadata=None):  # noqa: E501
        """CalEngTemplate - a model defined in Swagger

        :param metadata: The metadata of this CalEngTemplate.  # noqa: E501
        :type metadata: ObservationMetadata
        """
        self.swagger_types = {
            'metadata': ObservationMetadata
        }

        self.attribute_map = {
            'metadata': 'metadata'
        }
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'CalEngTemplate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CalEngTemplate of this CalEngTemplate.  # noqa: E501
        :rtype: CalEngTemplate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> ObservationMetadata:
        """Gets the metadata of this CalEngTemplate.


        :return: The metadata of this CalEngTemplate.
        :rtype: ObservationMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: ObservationMetadata):
        """Sets the metadata of this CalEngTemplate.


        :param metadata: The metadata of this CalEngTemplate.
        :type metadata: ObservationMetadata
        """
        if metadata is None:
            raise ValueError("Invalid value for `metadata`, must not be `None`")  # noqa: E501

        self._metadata = metadata
