# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana import util


class CalEngParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, det1_exp_time: float=None, det1_exp_number: int=None, det2_exp_time: float=None, det2_exp_number: int=None):  # noqa: E501
        """CalEngParameters - a model defined in Swagger

        :param det1_exp_time: The det1_exp_time of this CalEngParameters.  # noqa: E501
        :type det1_exp_time: float
        :param det1_exp_number: The det1_exp_number of this CalEngParameters.  # noqa: E501
        :type det1_exp_number: int
        :param det2_exp_time: The det2_exp_time of this CalEngParameters.  # noqa: E501
        :type det2_exp_time: float
        :param det2_exp_number: The det2_exp_number of this CalEngParameters.  # noqa: E501
        :type det2_exp_number: int
        """
        self.swagger_types = {
            'det1_exp_time': float,
            'det1_exp_number': int,
            'det2_exp_time': float,
            'det2_exp_number': int
        }

        self.attribute_map = {
            'det1_exp_time': 'det1_exp_time',
            'det1_exp_number': 'det1_exp_number',
            'det2_exp_time': 'det2_exp_time',
            'det2_exp_number': 'det2_exp_number'
        }
        self._det1_exp_time = det1_exp_time
        self._det1_exp_number = det1_exp_number
        self._det2_exp_time = det2_exp_time
        self._det2_exp_number = det2_exp_number

    @classmethod
    def from_dict(cls, dikt) -> 'CalEngParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CalEngParameters of this CalEngParameters.  # noqa: E501
        :rtype: CalEngParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def det1_exp_time(self) -> float:
        """Gets the det1_exp_time of this CalEngParameters.


        :return: The det1_exp_time of this CalEngParameters.
        :rtype: float
        """
        return self._det1_exp_time

    @det1_exp_time.setter
    def det1_exp_time(self, det1_exp_time: float):
        """Sets the det1_exp_time of this CalEngParameters.


        :param det1_exp_time: The det1_exp_time of this CalEngParameters.
        :type det1_exp_time: float
        """
        if det1_exp_time is None:
            raise ValueError("Invalid value for `det1_exp_time`, must not be `None`")  # noqa: E501

        self._det1_exp_time = det1_exp_time

    @property
    def det1_exp_number(self) -> int:
        """Gets the det1_exp_number of this CalEngParameters.


        :return: The det1_exp_number of this CalEngParameters.
        :rtype: int
        """
        return self._det1_exp_number

    @det1_exp_number.setter
    def det1_exp_number(self, det1_exp_number: int):
        """Sets the det1_exp_number of this CalEngParameters.


        :param det1_exp_number: The det1_exp_number of this CalEngParameters.
        :type det1_exp_number: int
        """
        if det1_exp_number is None:
            raise ValueError("Invalid value for `det1_exp_number`, must not be `None`")  # noqa: E501

        self._det1_exp_number = det1_exp_number

    @property
    def det2_exp_time(self) -> float:
        """Gets the det2_exp_time of this CalEngParameters.


        :return: The det2_exp_time of this CalEngParameters.
        :rtype: float
        """
        return self._det2_exp_time

    @det2_exp_time.setter
    def det2_exp_time(self, det2_exp_time: float):
        """Sets the det2_exp_time of this CalEngParameters.


        :param det2_exp_time: The det2_exp_time of this CalEngParameters.
        :type det2_exp_time: float
        """

        self._det2_exp_time = det2_exp_time

    @property
    def det2_exp_number(self) -> int:
        """Gets the det2_exp_number of this CalEngParameters.


        :return: The det2_exp_number of this CalEngParameters.
        :rtype: int
        """
        return self._det2_exp_number

    @det2_exp_number.setter
    def det2_exp_number(self, det2_exp_number: int):
        """Sets the det2_exp_number of this CalEngParameters.


        :param det2_exp_number: The det2_exp_number of this CalEngParameters.
        :type det2_exp_number: int
        """

        self._det2_exp_number = det2_exp_number
