# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana.models.common_parameters_metadata import CommonParametersMetadata  # noqa: F401,E501
from papahana import util


class CommonParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metadata: CommonParametersMetadata=None):  # noqa: E501
        """CommonParameters - a model defined in Swagger

        :param metadata: The metadata of this CommonParameters.  # noqa: E501
        :type metadata: CommonParametersMetadata
        """
        self.swagger_types = {
            'metadata': CommonParametersMetadata
        }

        self.attribute_map = {
            'metadata': 'metadata'
        }
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'CommonParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommonParameters of this CommonParameters.  # noqa: E501
        :rtype: CommonParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> CommonParametersMetadata:
        """Gets the metadata of this CommonParameters.


        :return: The metadata of this CommonParameters.
        :rtype: CommonParametersMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: CommonParametersMetadata):
        """Sets the metadata of this CommonParameters.


        :param metadata: The metadata of this CommonParameters.
        :type metadata: CommonParametersMetadata
        """
        if metadata is None:
            raise ValueError("Invalid value for `metadata`, must not be `None`")  # noqa: E501

        self._metadata = metadata
