# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana.models.date_schema import DateSchema  # noqa: F401,E501
from papahana import util


class Status(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, state: int=None, executions: List[DateSchema]=None, deleted: bool=False):  # noqa: E501
        """Status - a model defined in Swagger

        :param state: The state of this Status.  # noqa: E501
        :type state: int
        :param executions: The executions of this Status.  # noqa: E501
        :type executions: List[DateSchema]
        :param deleted: The deleted of this Status.  # noqa: E501
        :type deleted: bool
        """
        self.swagger_types = {
            'state': int,
            'executions': List[DateSchema],
            'deleted': bool
        }

        self.attribute_map = {
            'state': 'state',
            'executions': 'executions',
            'deleted': 'deleted'
        }
        self._state = state
        self._executions = executions
        self._deleted = deleted

    @classmethod
    def from_dict(cls, dikt) -> 'Status':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Status of this Status.  # noqa: E501
        :rtype: Status
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> int:
        """Gets the state of this Status.


        :return: The state of this Status.
        :rtype: int
        """
        return self._state

    @state.setter
    def state(self, state: int):
        """Sets the state of this Status.


        :param state: The state of this Status.
        :type state: int
        """

        self._state = state

    @property
    def executions(self) -> List[DateSchema]:
        """Gets the executions of this Status.


        :return: The executions of this Status.
        :rtype: List[DateSchema]
        """
        return self._executions

    @executions.setter
    def executions(self, executions: List[DateSchema]):
        """Sets the executions of this Status.


        :param executions: The executions of this Status.
        :type executions: List[DateSchema]
        """

        self._executions = executions

    @property
    def deleted(self) -> bool:
        """Gets the deleted of this Status.


        :return: The deleted of this Status.
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted: bool):
        """Sets the deleted of this Status.


        :param deleted: The deleted of this Status.
        :type deleted: bool
        """

        self._deleted = deleted
