# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana import util


class TargetMetadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, ui_name: str=None, template_type: str='target', version: str=None):  # noqa: E501
        """TargetMetadata - a model defined in Swagger

        :param name: The name of this TargetMetadata.  # noqa: E501
        :type name: str
        :param ui_name: The ui_name of this TargetMetadata.  # noqa: E501
        :type ui_name: str
        :param template_type: The template_type of this TargetMetadata.  # noqa: E501
        :type template_type: str
        :param version: The version of this TargetMetadata.  # noqa: E501
        :type version: str
        """
        self.swagger_types = {
            'name': str,
            'ui_name': str,
            'template_type': str,
            'version': str
        }

        self.attribute_map = {
            'name': 'name',
            'ui_name': 'ui_name',
            'template_type': 'template_type',
            'version': 'version'
        }
        self._name = name
        self._ui_name = ui_name
        self._template_type = template_type
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'TargetMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TargetMetadata of this TargetMetadata.  # noqa: E501
        :rtype: TargetMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this TargetMetadata.


        :return: The name of this TargetMetadata.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TargetMetadata.


        :param name: The name of this TargetMetadata.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def ui_name(self) -> str:
        """Gets the ui_name of this TargetMetadata.


        :return: The ui_name of this TargetMetadata.
        :rtype: str
        """
        return self._ui_name

    @ui_name.setter
    def ui_name(self, ui_name: str):
        """Sets the ui_name of this TargetMetadata.


        :param ui_name: The ui_name of this TargetMetadata.
        :type ui_name: str
        """
        if ui_name is None:
            raise ValueError("Invalid value for `ui_name`, must not be `None`")  # noqa: E501

        self._ui_name = ui_name

    @property
    def template_type(self) -> str:
        """Gets the template_type of this TargetMetadata.


        :return: The template_type of this TargetMetadata.
        :rtype: str
        """
        return self._template_type

    @template_type.setter
    def template_type(self, template_type: str):
        """Sets the template_type of this TargetMetadata.


        :param template_type: The template_type of this TargetMetadata.
        :type template_type: str
        """
        allowed_values = ["target"]  # noqa: E501
        if template_type not in allowed_values:
            raise ValueError(
                "Invalid value for `template_type` ({0}), must be one of {1}"
                .format(template_type, allowed_values)
            )

        self._template_type = template_type

    @property
    def version(self) -> str:
        """Gets the version of this TargetMetadata.


        :return: The version of this TargetMetadata.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this TargetMetadata.


        :param version: The version of this TargetMetadata.
        :type version: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version
