# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana import util


class TargetParametersTargetInfoMagnitude(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, target_info_band: str=None, target_info_mag: float=None):  # noqa: E501
        """TargetParametersTargetInfoMagnitude - a model defined in Swagger

        :param target_info_band: The target_info_band of this TargetParametersTargetInfoMagnitude.  # noqa: E501
        :type target_info_band: str
        :param target_info_mag: The target_info_mag of this TargetParametersTargetInfoMagnitude.  # noqa: E501
        :type target_info_mag: float
        """
        self.swagger_types = {
            'target_info_band': str,
            'target_info_mag': float
        }

        self.attribute_map = {
            'target_info_band': 'target_info_band',
            'target_info_mag': 'target_info_mag'
        }
        self._target_info_band = target_info_band
        self._target_info_mag = target_info_mag

    @classmethod
    def from_dict(cls, dikt) -> 'TargetParametersTargetInfoMagnitude':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TargetParameters_target_info_magnitude of this TargetParametersTargetInfoMagnitude.  # noqa: E501
        :rtype: TargetParametersTargetInfoMagnitude
        """
        return util.deserialize_model(dikt, cls)

    @property
    def target_info_band(self) -> str:
        """Gets the target_info_band of this TargetParametersTargetInfoMagnitude.


        :return: The target_info_band of this TargetParametersTargetInfoMagnitude.
        :rtype: str
        """
        return self._target_info_band

    @target_info_band.setter
    def target_info_band(self, target_info_band: str):
        """Sets the target_info_band of this TargetParametersTargetInfoMagnitude.


        :param target_info_band: The target_info_band of this TargetParametersTargetInfoMagnitude.
        :type target_info_band: str
        """

        self._target_info_band = target_info_band

    @property
    def target_info_mag(self) -> float:
        """Gets the target_info_mag of this TargetParametersTargetInfoMagnitude.


        :return: The target_info_mag of this TargetParametersTargetInfoMagnitude.
        :rtype: float
        """
        return self._target_info_mag

    @target_info_mag.setter
    def target_info_mag(self, target_info_mag: float):
        """Sets the target_info_mag of this TargetParametersTargetInfoMagnitude.


        :param target_info_mag: The target_info_mag of this TargetParametersTargetInfoMagnitude.
        :type target_info_mag: float
        """

        self._target_info_mag = target_info_mag
