# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana import util


class AcqProperties(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, wrap: str=None, rotmode: str=None, guider_po: str=None, ra_offset: str=None, dec_offset: str=None, guider_gs_ra: str=None, guider_gs_dec: str=None, guider_gs_mode: str=None):  # noqa: E501
        """AcqProperties - a model defined in Swagger

        :param wrap: The wrap of this AcqProperties.  # noqa: E501
        :type wrap: str
        :param rotmode: The rotmode of this AcqProperties.  # noqa: E501
        :type rotmode: str
        :param guider_po: The guider_po of this AcqProperties.  # noqa: E501
        :type guider_po: str
        :param ra_offset: The ra_offset of this AcqProperties.  # noqa: E501
        :type ra_offset: str
        :param dec_offset: The dec_offset of this AcqProperties.  # noqa: E501
        :type dec_offset: str
        :param guider_gs_ra: The guider_gs_ra of this AcqProperties.  # noqa: E501
        :type guider_gs_ra: str
        :param guider_gs_dec: The guider_gs_dec of this AcqProperties.  # noqa: E501
        :type guider_gs_dec: str
        :param guider_gs_mode: The guider_gs_mode of this AcqProperties.  # noqa: E501
        :type guider_gs_mode: str
        """
        self.swagger_types = {
            'wrap': str,
            'rotmode': str,
            'guider_po': str,
            'ra_offset': str,
            'dec_offset': str,
            'guider_gs_ra': str,
            'guider_gs_dec': str,
            'guider_gs_mode': str
        }

        self.attribute_map = {
            'wrap': 'wrap',
            'rotmode': 'rotmode',
            'guider_po': 'guider_po',
            'ra_offset': 'ra_offset',
            'dec_offset': 'dec_offset',
            'guider_gs_ra': 'guider_gs_ra',
            'guider_gs_dec': 'guider_gs_dec',
            'guider_gs_mode': 'guider_gs_mode'
        }
        self._wrap = wrap
        self._rotmode = rotmode
        self._guider_po = guider_po
        self._ra_offset = ra_offset
        self._dec_offset = dec_offset
        self._guider_gs_ra = guider_gs_ra
        self._guider_gs_dec = guider_gs_dec
        self._guider_gs_mode = guider_gs_mode

    @classmethod
    def from_dict(cls, dikt) -> 'AcqProperties':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Acq_properties of this AcqProperties.  # noqa: E501
        :rtype: AcqProperties
        """
        return util.deserialize_model(dikt, cls)

    @property
    def wrap(self) -> str:
        """Gets the wrap of this AcqProperties.


        :return: The wrap of this AcqProperties.
        :rtype: str
        """
        return self._wrap

    @wrap.setter
    def wrap(self, wrap: str):
        """Sets the wrap of this AcqProperties.


        :param wrap: The wrap of this AcqProperties.
        :type wrap: str
        """
        if wrap is None:
            raise ValueError("Invalid value for `wrap`, must not be `None`")  # noqa: E501

        self._wrap = wrap

    @property
    def rotmode(self) -> str:
        """Gets the rotmode of this AcqProperties.


        :return: The rotmode of this AcqProperties.
        :rtype: str
        """
        return self._rotmode

    @rotmode.setter
    def rotmode(self, rotmode: str):
        """Sets the rotmode of this AcqProperties.


        :param rotmode: The rotmode of this AcqProperties.
        :type rotmode: str
        """

        self._rotmode = rotmode

    @property
    def guider_po(self) -> str:
        """Gets the guider_po of this AcqProperties.


        :return: The guider_po of this AcqProperties.
        :rtype: str
        """
        return self._guider_po

    @guider_po.setter
    def guider_po(self, guider_po: str):
        """Sets the guider_po of this AcqProperties.


        :param guider_po: The guider_po of this AcqProperties.
        :type guider_po: str
        """

        self._guider_po = guider_po

    @property
    def ra_offset(self) -> str:
        """Gets the ra_offset of this AcqProperties.


        :return: The ra_offset of this AcqProperties.
        :rtype: str
        """
        return self._ra_offset

    @ra_offset.setter
    def ra_offset(self, ra_offset: str):
        """Sets the ra_offset of this AcqProperties.


        :param ra_offset: The ra_offset of this AcqProperties.
        :type ra_offset: str
        """

        self._ra_offset = ra_offset

    @property
    def dec_offset(self) -> str:
        """Gets the dec_offset of this AcqProperties.


        :return: The dec_offset of this AcqProperties.
        :rtype: str
        """
        return self._dec_offset

    @dec_offset.setter
    def dec_offset(self, dec_offset: str):
        """Sets the dec_offset of this AcqProperties.


        :param dec_offset: The dec_offset of this AcqProperties.
        :type dec_offset: str
        """

        self._dec_offset = dec_offset

    @property
    def guider_gs_ra(self) -> str:
        """Gets the guider_gs_ra of this AcqProperties.


        :return: The guider_gs_ra of this AcqProperties.
        :rtype: str
        """
        return self._guider_gs_ra

    @guider_gs_ra.setter
    def guider_gs_ra(self, guider_gs_ra: str):
        """Sets the guider_gs_ra of this AcqProperties.


        :param guider_gs_ra: The guider_gs_ra of this AcqProperties.
        :type guider_gs_ra: str
        """

        self._guider_gs_ra = guider_gs_ra

    @property
    def guider_gs_dec(self) -> str:
        """Gets the guider_gs_dec of this AcqProperties.


        :return: The guider_gs_dec of this AcqProperties.
        :rtype: str
        """
        return self._guider_gs_dec

    @guider_gs_dec.setter
    def guider_gs_dec(self, guider_gs_dec: str):
        """Sets the guider_gs_dec of this AcqProperties.


        :param guider_gs_dec: The guider_gs_dec of this AcqProperties.
        :type guider_gs_dec: str
        """

        self._guider_gs_dec = guider_gs_dec

    @property
    def guider_gs_mode(self) -> str:
        """Gets the guider_gs_mode of this AcqProperties.


        :return: The guider_gs_mode of this AcqProperties.
        :rtype: str
        """
        return self._guider_gs_mode

    @guider_gs_mode.setter
    def guider_gs_mode(self, guider_gs_mode: str):
        """Sets the guider_gs_mode of this AcqProperties.


        :param guider_gs_mode: The guider_gs_mode of this AcqProperties.
        :type guider_gs_mode: str
        """

        self._guider_gs_mode = guider_gs_mode
