# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AcqMetadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, ui_name: str=None, instrument: str=None, type: str=None, version: str=None, script: str=None):  # noqa: E501
        """AcqMetadata - a model defined in Swagger

        :param name: The name of this AcqMetadata.  # noqa: E501
        :type name: str
        :param ui_name: The ui_name of this AcqMetadata.  # noqa: E501
        :type ui_name: str
        :param instrument: The instrument of this AcqMetadata.  # noqa: E501
        :type instrument: str
        :param type: The type of this AcqMetadata.  # noqa: E501
        :type type: str
        :param version: The version of this AcqMetadata.  # noqa: E501
        :type version: str
        :param script: The script of this AcqMetadata.  # noqa: E501
        :type script: str
        """
        self.swagger_types = {
            'name': str,
            'ui_name': str,
            'instrument': str,
            'type': str,
            'version': str,
            'script': str
        }

        self.attribute_map = {
            'name': 'name',
            'ui_name': 'ui_name',
            'instrument': 'instrument',
            'type': 'type',
            'version': 'version',
            'script': 'script'
        }
        self._name = name
        self._ui_name = ui_name
        self._instrument = instrument
        self._type = type
        self._version = version
        self._script = script

    @classmethod
    def from_dict(cls, dikt) -> 'AcqMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Acq_metadata of this AcqMetadata.  # noqa: E501
        :rtype: AcqMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this AcqMetadata.


        :return: The name of this AcqMetadata.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AcqMetadata.


        :param name: The name of this AcqMetadata.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def ui_name(self) -> str:
        """Gets the ui_name of this AcqMetadata.


        :return: The ui_name of this AcqMetadata.
        :rtype: str
        """
        return self._ui_name

    @ui_name.setter
    def ui_name(self, ui_name: str):
        """Sets the ui_name of this AcqMetadata.


        :param ui_name: The ui_name of this AcqMetadata.
        :type ui_name: str
        """

        self._ui_name = ui_name

    @property
    def instrument(self) -> str:
        """Gets the instrument of this AcqMetadata.


        :return: The instrument of this AcqMetadata.
        :rtype: str
        """
        return self._instrument

    @instrument.setter
    def instrument(self, instrument: str):
        """Sets the instrument of this AcqMetadata.


        :param instrument: The instrument of this AcqMetadata.
        :type instrument: str
        """

        self._instrument = instrument

    @property
    def type(self) -> str:
        """Gets the type of this AcqMetadata.


        :return: The type of this AcqMetadata.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this AcqMetadata.


        :param type: The type of this AcqMetadata.
        :type type: str
        """

        self._type = type

    @property
    def version(self) -> str:
        """Gets the version of this AcqMetadata.


        :return: The version of this AcqMetadata.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this AcqMetadata.


        :param version: The version of this AcqMetadata.
        :type version: str
        """

        self._version = version

    @property
    def script(self) -> str:
        """Gets the script of this AcqMetadata.


        :return: The script of this AcqMetadata.
        :rtype: str
        """
        return self._script

    @script.setter
    def script(self, script: str):
        """Sets the script of this AcqMetadata.


        :param script: The script of this AcqMetadata.
        :type script: str
        """

        self._script = script
