# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana.models.instrument_enum import InstrumentEnum  # noqa: F401,E501
from papahana import util


class AcquisitionMetadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, ui_name: str=None, instrument: InstrumentEnum=None, template_type: str='acquisition', version: float=None, script: str=None):  # noqa: E501
        """AcquisitionMetadata - a model defined in Swagger

        :param name: The name of this AcquisitionMetadata.  # noqa: E501
        :type name: str
        :param ui_name: The ui_name of this AcquisitionMetadata.  # noqa: E501
        :type ui_name: str
        :param instrument: The instrument of this AcquisitionMetadata.  # noqa: E501
        :type instrument: InstrumentEnum
        :param template_type: The template_type of this AcquisitionMetadata.  # noqa: E501
        :type template_type: str
        :param version: The version of this AcquisitionMetadata.  # noqa: E501
        :type version: float
        :param script: The script of this AcquisitionMetadata.  # noqa: E501
        :type script: str
        """
        self.swagger_types = {
            'name': str,
            'ui_name': str,
            'instrument': InstrumentEnum,
            'template_type': str,
            'version': float,
            'script': str
        }

        self.attribute_map = {
            'name': 'name',
            'ui_name': 'ui_name',
            'instrument': 'instrument',
            'template_type': 'template_type',
            'version': 'version',
            'script': 'script'
        }
        self._name = name
        self._ui_name = ui_name
        self._instrument = instrument
        self._template_type = template_type
        self._version = version
        self._script = script

    @classmethod
    def from_dict(cls, dikt) -> 'AcquisitionMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AcquisitionMetadata of this AcquisitionMetadata.  # noqa: E501
        :rtype: AcquisitionMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this AcquisitionMetadata.


        :return: The name of this AcquisitionMetadata.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AcquisitionMetadata.


        :param name: The name of this AcquisitionMetadata.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def ui_name(self) -> str:
        """Gets the ui_name of this AcquisitionMetadata.


        :return: The ui_name of this AcquisitionMetadata.
        :rtype: str
        """
        return self._ui_name

    @ui_name.setter
    def ui_name(self, ui_name: str):
        """Sets the ui_name of this AcquisitionMetadata.


        :param ui_name: The ui_name of this AcquisitionMetadata.
        :type ui_name: str
        """

        self._ui_name = ui_name

    @property
    def instrument(self) -> InstrumentEnum:
        """Gets the instrument of this AcquisitionMetadata.


        :return: The instrument of this AcquisitionMetadata.
        :rtype: InstrumentEnum
        """
        return self._instrument

    @instrument.setter
    def instrument(self, instrument: InstrumentEnum):
        """Sets the instrument of this AcquisitionMetadata.


        :param instrument: The instrument of this AcquisitionMetadata.
        :type instrument: InstrumentEnum
        """

        self._instrument = instrument

    @property
    def template_type(self) -> str:
        """Gets the template_type of this AcquisitionMetadata.


        :return: The template_type of this AcquisitionMetadata.
        :rtype: str
        """
        return self._template_type

    @template_type.setter
    def template_type(self, template_type: str):
        """Sets the template_type of this AcquisitionMetadata.


        :param template_type: The template_type of this AcquisitionMetadata.
        :type template_type: str
        """
        allowed_values = ["acquisition"]  # noqa: E501
        if template_type not in allowed_values:
            raise ValueError(
                "Invalid value for `template_type` ({0}), must be one of {1}"
                .format(template_type, allowed_values)
            )

        self._template_type = template_type

    @property
    def version(self) -> float:
        """Gets the version of this AcquisitionMetadata.


        :return: The version of this AcquisitionMetadata.
        :rtype: float
        """
        return self._version

    @version.setter
    def version(self, version: float):
        """Sets the version of this AcquisitionMetadata.


        :param version: The version of this AcquisitionMetadata.
        :type version: float
        """

        self._version = version

    @property
    def script(self) -> str:
        """Gets the script of this AcquisitionMetadata.


        :return: The script of this AcquisitionMetadata.
        :rtype: str
        """
        return self._script

    @script.setter
    def script(self, script: str):
        """Sets the script of this AcquisitionMetadata.


        :param script: The script of this AcquisitionMetadata.
        :type script: str
        """

        self._script = script
