# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana import util


class InstrumentEnum(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    KCWI = "KCWI"
    DEIMOS = "DEIMOS"
    ESI = "ESI"
    HIRES = "HIRES"
    LRIS = "LRIS"
    MOSFIRE = "MOSFIRE"
    OSIRIS = "OSIRIS"
    NIRES = "NIRES"
    NIRC2 = "NIRC2"
    KCWI = "kcwi"
    DEIMOS = "deimos"
    ESI = "esi"
    HIRES = "hires"
    LRIS = "lris"
    MOSFIRE = "mosfire"
    OSIRIS = "osiris"
    NIRES = "nires"
    NIRC2 = "nirc2"
    DE = "DE"
    DF = "DF"
    EI = "EI"
    HI = "HI"
    KB = "KB"
    KF = "KF"
    LB = "LB"
    LR = "LR"
    MF = "MF"
    OI = "OI"
    OS = "OS"
    NR = "NR"
    NI = "NI"
    NS = "NS"
    N2 = "N2"
    NC = "NC"
    def __init__(self):  # noqa: E501
        """InstrumentEnum - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'InstrumentEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InstrumentEnum of this InstrumentEnum.  # noqa: E501
        :rtype: InstrumentEnum
        """
        return util.deserialize_model(dikt, cls)
