# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana.models.observation_metadata import ObservationMetadata  # noqa: F401,E501
from papahana.models.template_id_schema import TemplateIdSchema  # noqa: F401,E501
from papahana import util


class ObservationTemplate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metadata: List[ObservationMetadata]=None, template_index: TemplateIdSchema=None):  # noqa: E501
        """ObservationTemplate - a model defined in Swagger

        :param metadata: The metadata of this ObservationTemplate.  # noqa: E501
        :type metadata: List[ObservationMetadata]
        :param template_index: The template_index of this ObservationTemplate.  # noqa: E501
        :type template_index: TemplateIdSchema
        """
        self.swagger_types = {
            'metadata': List[ObservationMetadata],
            'template_index': TemplateIdSchema
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'template_index': 'template_index'
        }
        self._metadata = metadata
        self._template_index = template_index

    @classmethod
    def from_dict(cls, dikt) -> 'ObservationTemplate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ObservationTemplate of this ObservationTemplate.  # noqa: E501
        :rtype: ObservationTemplate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> List[ObservationMetadata]:
        """Gets the metadata of this ObservationTemplate.


        :return: The metadata of this ObservationTemplate.
        :rtype: List[ObservationMetadata]
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: List[ObservationMetadata]):
        """Sets the metadata of this ObservationTemplate.


        :param metadata: The metadata of this ObservationTemplate.
        :type metadata: List[ObservationMetadata]
        """

        self._metadata = metadata

    @property
    def template_index(self) -> TemplateIdSchema:
        """Gets the template_index of this ObservationTemplate.


        :return: The template_index of this ObservationTemplate.
        :rtype: TemplateIdSchema
        """
        return self._template_index

    @template_index.setter
    def template_index(self, template_index: TemplateIdSchema):
        """Sets the template_index of this ObservationTemplate.


        :param template_index: The template_index of this ObservationTemplate.
        :type template_index: TemplateIdSchema
        """

        self._template_index = template_index
