# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana.models.metadata import Metadata  # noqa: F401,E501
from papahana.models.observation import Observation  # noqa: F401,E501
from papahana.models.status import Status  # noqa: F401,E501
from papahana import util


class ObservationBlock(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, metadata: Metadata=None, observations: List[Observation]=None, associations: List[str]=None, observation_type: List[str]=None, priority: float=None, status: Status=None, comment: str=None):  # noqa: E501
        """ObservationBlock - a model defined in Swagger

        :param id: The id of this ObservationBlock.  # noqa: E501
        :type id: str
        :param metadata: The metadata of this ObservationBlock.  # noqa: E501
        :type metadata: Metadata
        :param observations: The observations of this ObservationBlock.  # noqa: E501
        :type observations: List[Observation]
        :param associations: The associations of this ObservationBlock.  # noqa: E501
        :type associations: List[str]
        :param observation_type: The observation_type of this ObservationBlock.  # noqa: E501
        :type observation_type: List[str]
        :param priority: The priority of this ObservationBlock.  # noqa: E501
        :type priority: float
        :param status: The status of this ObservationBlock.  # noqa: E501
        :type status: Status
        :param comment: The comment of this ObservationBlock.  # noqa: E501
        :type comment: str
        """
        self.swagger_types = {
            'id': str,
            'metadata': Metadata,
            'observations': List[Observation],
            'associations': List[str],
            'observation_type': List[str],
            'priority': float,
            'status': Status,
            'comment': str
        }

        self.attribute_map = {
            'id': 'id',
            'metadata': 'metadata',
            'observations': 'observations',
            'associations': 'associations',
            'observation_type': 'observation_type',
            'priority': 'priority',
            'status': 'status',
            'comment': 'comment'
        }
        self._id = id
        self._metadata = metadata
        self._observations = observations
        self._associations = associations
        self._observation_type = observation_type
        self._priority = priority
        self._status = status
        self._comment = comment

    @classmethod
    def from_dict(cls, dikt) -> 'ObservationBlock':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ObservationBlock of this ObservationBlock.  # noqa: E501
        :rtype: ObservationBlock
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ObservationBlock.


        :return: The id of this ObservationBlock.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ObservationBlock.


        :param id: The id of this ObservationBlock.
        :type id: str
        """

        self._id = id

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this ObservationBlock.


        :return: The metadata of this ObservationBlock.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this ObservationBlock.


        :param metadata: The metadata of this ObservationBlock.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def observations(self) -> List[Observation]:
        """Gets the observations of this ObservationBlock.


        :return: The observations of this ObservationBlock.
        :rtype: List[Observation]
        """
        return self._observations

    @observations.setter
    def observations(self, observations: List[Observation]):
        """Sets the observations of this ObservationBlock.


        :param observations: The observations of this ObservationBlock.
        :type observations: List[Observation]
        """

        self._observations = observations

    @property
    def associations(self) -> List[str]:
        """Gets the associations of this ObservationBlock.


        :return: The associations of this ObservationBlock.
        :rtype: List[str]
        """
        return self._associations

    @associations.setter
    def associations(self, associations: List[str]):
        """Sets the associations of this ObservationBlock.


        :param associations: The associations of this ObservationBlock.
        :type associations: List[str]
        """

        self._associations = associations

    @property
    def observation_type(self) -> List[str]:
        """Gets the observation_type of this ObservationBlock.


        :return: The observation_type of this ObservationBlock.
        :rtype: List[str]
        """
        return self._observation_type

    @observation_type.setter
    def observation_type(self, observation_type: List[str]):
        """Sets the observation_type of this ObservationBlock.


        :param observation_type: The observation_type of this ObservationBlock.
        :type observation_type: List[str]
        """

        self._observation_type = observation_type

    @property
    def priority(self) -> float:
        """Gets the priority of this ObservationBlock.


        :return: The priority of this ObservationBlock.
        :rtype: float
        """
        return self._priority

    @priority.setter
    def priority(self, priority: float):
        """Sets the priority of this ObservationBlock.


        :param priority: The priority of this ObservationBlock.
        :type priority: float
        """

        self._priority = priority

    @property
    def status(self) -> Status:
        """Gets the status of this ObservationBlock.


        :return: The status of this ObservationBlock.
        :rtype: Status
        """
        return self._status

    @status.setter
    def status(self, status: Status):
        """Sets the status of this ObservationBlock.


        :param status: The status of this ObservationBlock.
        :type status: Status
        """

        self._status = status

    @property
    def comment(self) -> str:
        """Gets the comment of this ObservationBlock.


        :return: The comment of this ObservationBlock.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment: str):
        """Sets the comment of this ObservationBlock.


        :param comment: The comment of this ObservationBlock.
        :type comment: str
        """

        self._comment = comment
