# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana import util


class OneOfSemIdSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """OneOfSemIdSchema - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OneOfSemIdSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OneOfSemIdSchema of this OneOfSemIdSchema.  # noqa: E501
        :rtype: OneOfSemIdSchema
        """
        return util.deserialize_model(dikt, cls)
