# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana import util


class ProgramInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, containers: List[str]=None, ob_blocks: List[str]=None):  # noqa: E501
        """ProgramInfo - a model defined in Swagger

        :param containers: The containers of this ProgramInfo.  # noqa: E501
        :type containers: List[str]
        :param ob_blocks: The ob_blocks of this ProgramInfo.  # noqa: E501
        :type ob_blocks: List[str]
        """
        self.swagger_types = {
            'containers': List[str],
            'ob_blocks': List[str]
        }

        self.attribute_map = {
            'containers': 'containers',
            'ob_blocks': 'ob_blocks'
        }
        self._containers = containers
        self._ob_blocks = ob_blocks

    @classmethod
    def from_dict(cls, dikt) -> 'ProgramInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProgramInfo of this ProgramInfo.  # noqa: E501
        :rtype: ProgramInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def containers(self) -> List[str]:
        """Gets the containers of this ProgramInfo.


        :return: The containers of this ProgramInfo.
        :rtype: List[str]
        """
        return self._containers

    @containers.setter
    def containers(self, containers: List[str]):
        """Sets the containers of this ProgramInfo.


        :param containers: The containers of this ProgramInfo.
        :type containers: List[str]
        """

        self._containers = containers

    @property
    def ob_blocks(self) -> List[str]:
        """Gets the ob_blocks of this ProgramInfo.


        :return: The ob_blocks of this ProgramInfo.
        :rtype: List[str]
        """
        return self._ob_blocks

    @ob_blocks.setter
    def ob_blocks(self, ob_blocks: List[str]):
        """Sets the ob_blocks of this ProgramInfo.


        :param ob_blocks: The ob_blocks of this ProgramInfo.
        :type ob_blocks: List[str]
        """

        self._ob_blocks = ob_blocks
