# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from papahana.models.base_model_ import Model
from papahana.models.dec_schema import DecSchema  # noqa: F401,E501
from papahana.models.ra_schema import RASchema  # noqa: F401,E501
from papahana import util


class TargetParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, target_info_name: str=None, target_coord_ra: RASchema=None, target_coord_dec: DecSchema=None):  # noqa: E501
        """TargetParameters - a model defined in Swagger

        :param target_info_name: The target_info_name of this TargetParameters.  # noqa: E501
        :type target_info_name: str
        :param target_coord_ra: The target_coord_ra of this TargetParameters.  # noqa: E501
        :type target_coord_ra: RASchema
        :param target_coord_dec: The target_coord_dec of this TargetParameters.  # noqa: E501
        :type target_coord_dec: DecSchema
        """
        self.swagger_types = {
            'target_info_name': str,
            'target_coord_ra': RASchema,
            'target_coord_dec': DecSchema
        }

        self.attribute_map = {
            'target_info_name': 'target_info_name',
            'target_coord_ra': 'target_coord_ra',
            'target_coord_dec': 'target_coord_dec'
        }
        self._target_info_name = target_info_name
        self._target_coord_ra = target_coord_ra
        self._target_coord_dec = target_coord_dec

    @classmethod
    def from_dict(cls, dikt) -> 'TargetParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TargetParameters of this TargetParameters.  # noqa: E501
        :rtype: TargetParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def target_info_name(self) -> str:
        """Gets the target_info_name of this TargetParameters.


        :return: The target_info_name of this TargetParameters.
        :rtype: str
        """
        return self._target_info_name

    @target_info_name.setter
    def target_info_name(self, target_info_name: str):
        """Sets the target_info_name of this TargetParameters.


        :param target_info_name: The target_info_name of this TargetParameters.
        :type target_info_name: str
        """
        if target_info_name is None:
            raise ValueError("Invalid value for `target_info_name`, must not be `None`")  # noqa: E501

        self._target_info_name = target_info_name

    @property
    def target_coord_ra(self) -> RASchema:
        """Gets the target_coord_ra of this TargetParameters.


        :return: The target_coord_ra of this TargetParameters.
        :rtype: RASchema
        """
        return self._target_coord_ra

    @target_coord_ra.setter
    def target_coord_ra(self, target_coord_ra: RASchema):
        """Sets the target_coord_ra of this TargetParameters.


        :param target_coord_ra: The target_coord_ra of this TargetParameters.
        :type target_coord_ra: RASchema
        """
        if target_coord_ra is None:
            raise ValueError("Invalid value for `target_coord_ra`, must not be `None`")  # noqa: E501

        self._target_coord_ra = target_coord_ra

    @property
    def target_coord_dec(self) -> DecSchema:
        """Gets the target_coord_dec of this TargetParameters.


        :return: The target_coord_dec of this TargetParameters.
        :rtype: DecSchema
        """
        return self._target_coord_dec

    @target_coord_dec.setter
    def target_coord_dec(self, target_coord_dec: DecSchema):
        """Sets the target_coord_dec of this TargetParameters.


        :param target_coord_dec: The target_coord_dec of this TargetParameters.
        :type target_coord_dec: DecSchema
        """
        if target_coord_dec is None:
            raise ValueError("Invalid value for `target_coord_dec`, must not be `None`")  # noqa: E501

        self._target_coord_dec = target_coord_dec
